### ISSUE TITLE
Add [mysqld] to my.cnf to avoid mysql error on initial vagrant up

### ISSUE THREAD

**Issue by onevoltaicpile** [olivatecnologia/vagrant-moodlebox#3]
After running `vagrant up` for the first time, I encountered the following error:
`[ERROR] Found option without preceding group in config file /etc/mysql/my.cnf at line 19!`

Adding `[mysqld]` to `/etc/mysql/my.cnf` just below the comments resolves this issue for me.

Versions: Vagrant 1.8.6, VirtualBox 5.0.26

**Comment by heitorsilva** [comment]
Which version of MySql was installed to you?

**Comment by onevoltaicpile** [comment]
5.7.15

**Comment by anthonywalters** [comment]
Just to let you know - I had this issue too. I added the same fix as aaronjustcode.

**Comment by heitorsilva** [comment]
Problem solved with commit 2b381ba!
